### ISSUE TITLE
When utilizing Data Point Graph 2.0 in Reports section, it does not permit any asset selection to be done

### ISSUE THREAD

**Issue by rahultsag** [Cumulocity-IoT/cumulocity-community-plugins#24]
While trying to add a widget in reports the asset selection doesn't display the correct asset list...while some other standard widgets is able to display the right list of assets.

![ Cumulocity - Cockpit 2023-11-27 16-30-18](https://github.com/SoftwareAG/cumulocity-community-plugins/assets/116082992/426caff7-3044-49a1-90e2-523ddd35317c)

**Comment by eniosultan** [comment]
Fixed in #36
