### ISSUE TITLE
Display options for aggregations can be simplified

### ISSUE THREAD

**Issue by rahultsag** [Cumulocity-IoT/cumulocity-community-plugins#33]
Currently, the option under "Display Options" is "Display aggregation selection on view". This consist of unnecessary repetition of word "display". It can be optimized as below with only "Aggregation options" or "Aggregation Selection"

Display Options 
- Time Range Selector
- Aggregation Options
- Y-Axis Helper Lines
- X-Axis Helper Lines

**Comment by eniosultan** [comment]
Issue fixed in the following PR:

https://github.com/Cumulocity-IoT/cumulocity-community-plugins/pull/46
