### ISSUE TITLE
When real-time time is selected the date/time selector is not greyed out

### ISSUE THREAD

**Issue by rahultsag** [Cumulocity-IoT/cumulocity-community-plugins#34]
When "Realtime" is selected, the date/time selector on the view is not greyed out. Although it doesnt allow changing the time, the active appearance can mislead users into thinking they can select differnt time range.

![grafik](https://github.com/SoftwareAG/cumulocity-community-plugins/assets/116082992/bb60dec3-fe4e-477e-b1bc-7e2dd4b84a41)

**Comment by eniosultan** [comment]
Issue fixed in the following PR:

https://github.com/Cumulocity-IoT/cumulocity-community-plugins/pull/46
