### ISSUE TITLE
Default widget width not defined/looks broken

### ISSUE THREAD

**Issue by beabehnisch** [Cumulocity-IoT/cumulocity-community-plugins#39]
**Describe the bug**
Compared with the earlier version, the new datapoint graph has a different default width define, which makes the widget look broken on default/whenever added

**To Reproduce
**
1. Edit widgets
2. Select new (vs. old) datapoint graph widget
3. Add

**Expected behavior**
a good default size that doesn't look broken/always require a resizing to be usable
(maybe even a minimum size, if the widget doesn't work smaller anyway)

**Screenshots**
![Screenshot 2024-08-21 at 13 55 30](https://github.com/user-attachments/assets/10674842-6de3-4c06-96f0-fe66da48626d)

**Comment by eniosultan** [comment]
Issue fixed in the following PR:

https://github.com/Cumulocity-IoT/cumulocity-community-plugins/pull/46
