### ISSUE TITLE
Merge Y axis of datapoints with the same range and unit

### ISSUE THREAD

**Issue by jakubdrewniak** [Cumulocity-IoT/cumulocity-community-plugins#4]
**Is your feature request related to a problem? Please describe.**
As each datapoint has it's own Y axis, it can lead to a situation where Y axis takes large part of widget. See comparison of legacy data points graph and it's new implementation
![image](https://user-images.githubusercontent.com/38259738/233354759-3d166737-b90c-4abf-b949-5dbff1ee5cb9.png)

**Describe the solution you'd like**
Assign one Y axis for datapoints that have same range (min and max value) and unit. Indicate which Y axis is related to specific data point.

**Describe alternatives you've considered**
n/a

**Additional context**

**Comment by sagIoTPower** [comment]
Hi, I have a similar request. The details can be found [here](https://tech.forums.softwareag.com/t/single-y-axis-when-choosing-multiple-datapoints/285448).

**Comment by jmoo900** [comment]
I have a customer that would like this functionality to be included as well.  This would make it in line with the out of the box version of the widget.

**Comment by janhommes** [comment]
@jmoo900 we see the need but at the moment have no capacity to work on this. We will come back later to this topic, when we will also include alarms and events into this widget (planned for next year). If you need it earlier, feal free to contribute with a pull request.

**Comment by beabehnisch** [comment]
+1 :) – we just had a session with a customer yesterday, that also needs the merging-y-axis to be supported in order to be able to move from the old to the new Datapoint graph widget

**Comment by haraldmeyer** [comment]
Another vote, yes please.

**Comment by eniosultan** [comment]
Issue fixed in the following PR:

https://github.com/Cumulocity-IoT/cumulocity-community-plugins/pull/46
