### ISSUE TITLE
Option to show legend – especially unit – on the axes (similar as before)

### ISSUE THREAD

**Issue by beabehnisch** [Cumulocity-IoT/cumulocity-community-plugins#40]
**Is your feature request related to a problem? Please describe.**
As an end-user who is used to work with data, I expect data graph to always have a clear legend – especially a UNIT! – right next to the axes (especially on y-axis) in order to make clear what the numbers actually mean. Currently there is no unit visible at all (even in the pills on top)

**Describe the solution you'd like**
- Minimum: At least the units should be visible
- better: enabling users to show a – configurable – legend right on the y-axis similar to the way it was before (see screenshot below) 
- ideally: also improve readability of the label (compared to the old DP graph) – could mean bigger size font/more contrast or maybe just using UPPERCASE?!.
![Screenshot 2024-08-21 at 16 32 49](https://github.com/user-attachments/assets/e63978d5-24b9-43af-8d5e-19247f521eff)

**Describe alternatives you've considered**
While some of the information is still there (as pills on top of the graph) and definitely easier to read as before, the unit is currently missing – and the connection to the graph is not that easy to understand anymore – especially for new and occasional users.

**Additional context**
/

**Comment by eniosultan** [comment]
Issue fixed in the following PR:

https://github.com/Cumulocity-IoT/cumulocity-community-plugins/pull/46
