### ISSUE TITLE
Data Points Graph: trying to disable last data point breaks the widget

### ISSUE THREAD

**Issue by haraldmeyer** [Cumulocity-IoT/cumulocity-community-plugins#43]
**Describe the bug**
When multiple datapoints are configured it is possible to disable some of them so that they are not shown. At least one datapoint needs to be kept enabled. The problem is when one tries to disable the last datapoint the corresponding alert is not just affecting the current datapoint but all other datapoints. At that point, it is not possible to re-enable the other datapoints and the dashboard has to be reloaded.

**To Reproduce**
1. Configure three datapoints A, B, C
2. Disable datapoints A,B
3. Try to disable datapoint C
4. Warning is shown for all three datapoints and toggling the status is disabled for all of them.

**Expected behavior**
Warning should only affect current datapoint. It should be possible to enable another datapoint. The warning on the previous datapoint should go away and it should be possible to disable it now.

**Screenshots**

![image](https://github.com/user-attachments/assets/ae50195b-5313-4472-8c4c-7705cb58fb85)

**Desktop (please complete the following information):**
 - OS: Win 11
 - Browser Chrome
 - Version 128.0.6613.113

**Comment by eniosultan** [comment]
Issue fixed in the following PR:

https://github.com/Cumulocity-IoT/cumulocity-community-plugins/pull/46
